"""initial schema

Revision ID: 0afdabe1440b
Revises: 295722036856
Create Date: 2026-07-12 15:55:53.344220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afdabe1440b'
down_revision: Union[str, Sequence[str], None] = '295722036856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('org_id', sa.String(length=1), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('tourn_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purse', sa.Integer(), nullable=True),
    sa.Column('fedex_cup_points', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('week_number', sa.String(length=4), nullable=True),
    sa.Column('format', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('time_zone', sa.String(length=200), nullable=True),
    sa.Column('course_id', sa.String(length=16), nullable=True),
    sa.Column('course_name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tourn_id')
    )
    op.create_index(op.f('ix_tournaments_tourn_id'), 'tournaments', ['tourn_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('earnings',
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('tourn_id', sa.String(length=16), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['tourn_id'], ['tournaments.tourn_id'], ),
    sa.PrimaryKeyConstraint('year', 'tourn_id', 'player_id')
    )
    op.create_index(op.f('ix_earnings_player_id'), 'earnings', ['player_id'], unique=False)
    op.create_index(op.f('ix_earnings_tourn_id'), 'earnings', ['tourn_id'], unique=False)
    op.create_index(op.f('ix_earnings_year'), 'earnings', ['year'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('org_id', sa.String(length=1), nullable=False),
    sa.Column('tourn_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('week_number', sa.String(length=4), nullable=False),
    sa.Column('purse', sa.Integer(), nullable=False),
    sa.Column('winners_share', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tourn_id'], ['tournaments.tourn_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_tourn_id'), 'schedules', ['tourn_id'], unique=False)
    op.create_index(op.f('ix_schedules_week_number'), 'schedules', ['week_number'], unique=False)
    op.create_index(op.f('ix_schedules_year'), 'schedules', ['year'], unique=False)
    op.create_table('tournament_leaderboard',
    sa.Column('org_id', sa.String(length=1), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('tourn_id', sa.String(length=16), nullable=False),
    sa.Column('tourn_status', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('round_status', sa.String(length=32), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('cut_line', sa.String(length=4), nullable=True),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('tourn_position', sa.String(length=8), nullable=False),
    sa.Column('total_score', sa.String(length=4), nullable=False),
    sa.Column('current_round_score', sa.String(length=4), nullable=False),
    sa.Column('round_complete', sa.Boolean(), nullable=False),
    sa.Column('thru', sa.String(length=4), nullable=False),
    sa.Column('tee_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['tourn_id'], ['tournaments.tourn_id'], ),
    sa.PrimaryKeyConstraint('year', 'tourn_id', 'round_id', 'player_id')
    )
    op.create_index(op.f('ix_tournament_leaderboard_org_id'), 'tournament_leaderboard', ['org_id'], unique=False)
    op.create_index(op.f('ix_tournament_leaderboard_player_id'), 'tournament_leaderboard', ['player_id'], unique=False)
    op.create_index(op.f('ix_tournament_leaderboard_round_id'), 'tournament_leaderboard', ['round_id'], unique=False)
    op.create_index(op.f('ix_tournament_leaderboard_tourn_id'), 'tournament_leaderboard', ['tourn_id'], unique=False)
    op.create_index(op.f('ix_tournament_leaderboard_year'), 'tournament_leaderboard', ['year'], unique=False)
    op.create_table('pool_leaderboards',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('year', 'pool_id', 'user_id')
    )
    op.create_index(op.f('ix_pool_leaderboards_pool_id'), 'pool_leaderboards', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_leaderboards_user_id'), 'pool_leaderboards', ['user_id'], unique=False)
    op.create_index(op.f('ix_pool_leaderboards_year'), 'pool_leaderboards', ['year'], unique=False)
    op.create_table('pool_memberships',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pool_id', 'user_id')
    )
    op.create_index(op.f('ix_pool_memberships_pool_id'), 'pool_memberships', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_memberships_user_id'), 'pool_memberships', ['user_id'], unique=False)
    op.create_table('pool_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tourn_id', sa.String(length=16), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('week_number', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['tourn_id'], ['tournaments.tourn_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_picks_id'), 'pool_picks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_picks_id'), table_name='pool_picks')
    op.drop_table('pool_picks')
    op.drop_index(op.f('ix_pool_memberships_user_id'), table_name='pool_memberships')
    op.drop_index(op.f('ix_pool_memberships_pool_id'), table_name='pool_memberships')
    op.drop_table('pool_memberships')
    op.drop_index(op.f('ix_pool_leaderboards_year'), table_name='pool_leaderboards')
    op.drop_index(op.f('ix_pool_leaderboards_user_id'), table_name='pool_leaderboards')
    op.drop_index(op.f('ix_pool_leaderboards_pool_id'), table_name='pool_leaderboards')
    op.drop_table('pool_leaderboards')
    op.drop_index(op.f('ix_tournament_leaderboard_year'), table_name='tournament_leaderboard')
    op.drop_index(op.f('ix_tournament_leaderboard_tourn_id'), table_name='tournament_leaderboard')
    op.drop_index(op.f('ix_tournament_leaderboard_round_id'), table_name='tournament_leaderboard')
    op.drop_index(op.f('ix_tournament_leaderboard_player_id'), table_name='tournament_leaderboard')
    op.drop_index(op.f('ix_tournament_leaderboard_org_id'), table_name='tournament_leaderboard')
    op.drop_table('tournament_leaderboard')
    op.drop_index(op.f('ix_schedules_year'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_week_number'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_tourn_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_earnings_year'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_tourn_id'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_player_id'), table_name='earnings')
    op.drop_table('earnings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tournaments_tourn_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
